// ── Premium Unsplash image catalog ────────────────────────────────────────────
// All photos are freely usable under Unsplash License.
// Format: ?w=SIZE&q=85&fit=crop for consistent cropping + WebP compression.

const U = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=85&fit=crop&auto=format`

// ── Sacs à main ───────────────────────────────────────────────────────────────
const BAGS = {
  // 1 — Beige structured tote (tan leather)
  milanoMain:   U('1548036328-c9fa89d128fa'),
  milanoDetail: U('1566150905458-1bf1fc113f0d'),
  milanoLife:   U('1469334031218-e382a71b716b'),   // elegant woman

  // 2 — Gold-chain clutch / evening bag
  pochetteMain:   U('1584917865442-de89be144b2a'),
  pochetteDetail: U('1553062407-98eeb64c6a62'),
  pochetteLife:   U('1515886657613-9f3515b0c78f'),  // fashion Dubai

  // 3 — Woven raffia / tressé bag
  cabasMain:   U('1591561954557-26941169b49e'),
  cabasDetail: U('1548036328-c9fa89d128fa'),
  cabasLife:   U('1469334031218-e382a71b716b'),

  // 4 — Mini croco-embossed nude
  crocoMain:   U('1553062407-98eeb64c6a62'),
  crocoDetail: U('1566150905458-1bf1fc113f0d'),
  crocoLife:   U('1515886657613-9f3515b0c78f'),

  // 5 — Black sleek shoulder bag
  noirMain:   U('1566150905458-1bf1fc113f0d'),
  noirDetail: U('1553062407-98eeb64c6a62'),
  noirLife:   U('1469334031218-e382a71b716b'),

  // 6 — White chic summer bag
  blancMain:   U('1594938298603-c8148c4dae35'),
  blancDetail: U('1548036328-c9fa89d128fa'),
  blancLife:   U('1515886657613-9f3515b0c78f'),

  // 7 — Brown designer satchel
  marronMain:   U('1614252235316-8c857d38b5f4'),
  marronDetail: U('1553062407-98eeb64c6a62'),
  marronLife:   U('1469334031218-e382a71b716b'),

  // 8 — Fashion contemporary
  fashionMain:   U('1517841905240-472988babdf9'),
  fashionDetail: U('1584917865442-de89be144b2a'),
  fashionLife:   U('1515886657613-9f3515b0c78f'),
}

// ── Bijoux & Or ──────────────────────────────────────────────────────────────
// Or jaune (yellow gold) + Or blanc (white gold / plaqué argent)
const BIJOUX = {
  // Colliers / chaînes
  collierJauneMain:   U('1573408301185-9519eb7db41c'),  // gold chain necklace
  collierJauneDetail: U('1611591437281-460bfbe1220a'),  // gold chain closeup
  collierBlanc:       U('1515377905703-c4788e51af15'),  // white gold necklace

  // Bracelets
  braceletJauneMain:   U('1610397648930-477b8c7f0943'),  // stacked gold bracelets
  braceletJauneDetail: U('1602751584552-8ba73aad10e1'),  // delicate gold bracelet
  braceletBlanc:       U('1583845773-9e42e5e22d9f'),     // white gold bracelet

  // Boucles d'oreilles
  bouclesJauneMain:   U('1631982690223-8aa4e09da8a3'),  // gold hoop earrings
  bouclesJauneDetail: U('1576022162068-73b11b0f5bfc'),  // drop earrings
  bouclesBlanc:       U('1548036328-c9fa89d128fa'),     // silver earrings

  // Parure / sets
  parureMain:   U('1569397288884-4d43d6738fbd'),  // jewelry flatlay
  parureDetail: U('1606800052052-a08af7148866'),  // gold jewelry collection
  parureLife:   U('1573408301185-9519eb7db41c'),

  // Chaînes premium
  chaineJauneMain:   U('1611591437281-460bfbe1220a'),  // gold chain
  chaineJauneDetail: U('1573408301185-9519eb7db41c'),
  chaineBlanc:       U('1515377905703-c4788e51af15'),  // white gold chain
}

// ── Accessories ───────────────────────────────────────────────────────────────
const ACC = {
  bracelet:   U('1611085583191-a3b181a88401'),
  braceletD:  U('1602173574767-37ac01994b2a'),
  lunettes:   U('1509695507497-903c140c43b0'),
  lunettesD:  U('1577803645773-f96470509666'),
  ceinture:   U('1624623278313-a930126a11c3'),
  ceintureD:  U('1614252235316-8c857d38b5f4'),
  foulard:    U('1601924921557-45e6dea0a157'),
  foulardD:   U('1596755094514-f87e34085b2c'),
  parfum:     U('1541643600914-78b084683702'),
  parfumD:    U('1523293182086-39651edb684d'),
  robe:       U('1515886657613-9f3515b0c78f'),
  robeDet:    U('1469334031218-e382a71b716b'),
  chaussure:  U('1543163521-1bf539c55dd2'),
  chaussureD: U('1542291026-7eec264c27ff'),
}

// ── Parfums Arabes / Ibraq Collection ─────────────────────────────────────────
const PARFUMS = {
  // Flacons luxe fond blanc / ambiance orientale
  oudMain:       U('1547994787-e0f0e3c76dab', 800),
  oudDetail:     U('1541643600914-78b084683702', 800),
  oudLife:       U('1523293182086-39651edb684d', 800),

  roseMain:      U('1588776814546-daab30f310ce', 800),
  roseDetail:    U('1563170351-be9e0b7d6b4e', 800),
  roseLife:      U('1541643600914-78b084683702', 800),

  ambreMain:     U('1594736797933-d0501ba2fe65', 800),
  ambreDetail:   U('1547994787-e0f0e3c76dab', 800),
  ambreLife:     U('1523293182086-39651edb684d', 800),

  santalMain:    U('1563170351-be9e0b7d6b4e', 800),
  santalDetail:  U('1588776814546-daab30f310ce', 800),
  santalLife:    U('1541643600914-78b084683702', 800),

  muskMain:      U('1523293182086-39651edb684d', 800),
  muskDetail:    U('1547994787-e0f0e3c76dab', 800),
  muskLife:      U('1594736797933-d0501ba2fe65', 800),

  jasminMain:    U('1594736797933-d0501ba2fe65', 800),
  jasminDetail:  U('1563170351-be9e0b7d6b4e', 800),
  jasminLife:    U('1588776814546-daab30f310ce', 800),

  // Image catégorie / hero
  catMain:       U('1541643600914-78b084683702', 600),
}

// ─── Categories ───────────────────────────────────────────────────────────────
export const MOCK_CATEGORIES = [
  {
    id:          'cat-bags',
    name:        'Sacs à Main',
    slug:        'sacs-a-main',
    description: 'Collection exclusive de sacs à main de luxe importés de Dubaï',
    image:       '/images/SACCPRO.png',
    position:    1,
  },
  {
    id:          'cat-robes',
    name:        'Robes',
    slug:        'robes',
    description: 'Robes de luxe, de soirée et d\'été — style oriental premium',
    image:       '/images/ROBESLUXETURQUE.png',
    position:    2,
  },
  {
    id:          'cat-jeans',
    name:        'Jeans',
    slug:        'jeans',
    description: 'Jeans premium et denim tendance importés de Turquie',
    image:       'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=85&fit=crop&auto=format',
    position:    3,
  },
  {
    id:          'cat-tennis',
    name:        'Tennis & Sport',
    slug:        'tennis',
    description: 'Sportswear luxe et tennis style — confort et élégance',
    image:       '/images/tennis2.png',
    position:    4,
  },
  {
    id:          'cat-chaussures',
    name:        'Chaussures',
    slug:        'chaussures',
    description: 'Escarpins, sandales et bottines premium importés de Turquie',
    image:       '/images/chaussure1.png',
    position:    5,
  },
  {
    id:          'cat-bijoux',
    name:        'Bijoux & Or',
    slug:        'bijoux',
    description: 'Colliers, bracelets et parures en or — bijouterie fine de Dubaï',
    image:       BIJOUX.collierJauneMain,
    position:    6,
  },
  {
    id:          'cat-accessories',
    name:        'Accessoires',
    slug:        'accessoires',
    description: 'Bijoux, ceintures, foulards et lunettes de luxe',
    image:       U('1611085583191-a3b181a88401', 600),
    position:    7,
  },
  {
    id:          'cat-new',
    name:        'Nouveautés',
    slug:        'nouveautes',
    description: 'Les dernières pièces de la collection',
    image:       U('1584917865442-de89be144b2a', 600),
    position:    8,
  },
  {
    id:          'cat-bestsellers',
    name:        'Best Sellers',
    slug:        'best-sellers',
    description: 'Les pièces les plus appréciées',
    image:       U('1553062407-98eeb64c6a62', 600),
    position:    9,
  },
  {
    id:          'cat-parfum',
    name:        'Parfums Arabes',
    slug:        'parfums',
    description: 'Parfums orientaux 75 ml — collection Ibraq, oud, rose, ambre et musc de la Péninsule Arabique',
    image:       PARFUMS.catMain,
    position:    10,
  },
]

// ─── Products ─────────────────────────────────────────────────────────────────
export const MOCK_PRODUCTS = [
  // ── 1 ─ Sac Cuir Milano (Beige) ──────────────────────────────────────────
  {
    id:           'prod-1',
    name:         'Sac Cuir Milano',
    slug:         'sac-cuir-milano',
    description:  "Sac à main en cuir pleine fleur d'exception, façonné en Italie. Fermeture dorée, doublure en suède. La pièce emblématique de MA LUXURY.",
    price:        85,
    comparePrice: 90,
    images:       [BAGS.milanoMain, BAGS.milanoDetail, BAGS.milanoLife],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        12,
    tags:         ['cuir', 'luxe', 'bestseller'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  47,
    createdAt:    '2024-01-15T00:00:00Z',
    updatedAt:    '2024-01-15T00:00:00Z',
  },

  // ── 2 ─ Pochette Dorée Dubai ──────────────────────────────────────────────
  {
    id:           'prod-2',
    name:         'Pochette Dorée Dubai',
    slug:         'pochette-doree-dubai',
    description:  "Mini-pochette habillée aux reflets dorés, inspirée de l'architecture de Dubai. Chaîne amovible, intérieur en velours.",
    price:        55,
    comparePrice: 70,
    images:       [BAGS.pochetteMain, BAGS.pochetteDetail, BAGS.pochetteLife],
    categoryId:   'cat-new',
    category:     { id: 'cat-new', name: 'Nouveautés', slug: 'nouveautes', position: 3 },
    stock:        8,
    tags:         ['doré', 'soirée', 'nouveau'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  23,
    createdAt:    '2024-02-10T00:00:00Z',
    updatedAt:    '2024-02-10T00:00:00Z',
  },

  // ── 3 ─ Cabas Tressé Luxe ────────────────────────────────────────────────
  {
    id:           'prod-3',
    name:         'Cabas Tressé Luxe',
    slug:         'cabas-tresse-luxe',
    description:  "Grand cabas en cuir tressé à la main. Espace généreux, fermeture magnétique. Un investissement mode pour l'éternité.",
    price:        79,
    comparePrice: 90,
    images:       [BAGS.cabasMain, BAGS.cabasDetail, BAGS.cabasLife],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        5,
    tags:         ['tressé', 'grand format', 'artisanal'],
    featured:     true,
    active:       true,
    rating:       4.7,
    reviewCount:  31,
    createdAt:    '2024-01-20T00:00:00Z',
    updatedAt:    '2024-01-20T00:00:00Z',
  },

  // ── 4 ─ Mini Sac Croco Nude ──────────────────────────────────────────────
  {
    id:           'prod-4',
    name:         'Mini Sac Croco Nude',
    slug:         'mini-sac-croco-nude',
    description:  "Mini sac structuré en cuir embossé crocodile coloris nude. Attaches dorées, format compact. Iconique et intemporel.",
    price:        72,
    comparePrice: 85,
    images:       [BAGS.crocoMain, BAGS.crocoDetail, BAGS.crocoLife],
    categoryId:   'cat-bestsellers',
    category:     { id: 'cat-bestsellers', name: 'Best Sellers', slug: 'best-sellers', position: 4 },
    stock:        3,
    tags:         ['croco', 'mini', 'bestseller'],
    featured:     true,
    active:       true,
    rating:       5.0,
    reviewCount:  58,
    createdAt:    '2023-12-01T00:00:00Z',
    updatedAt:    '2023-12-01T00:00:00Z',
  },

  // ── 5 ─ Sac Noir Élégant ─────────────────────────────────────────────────
  {
    id:           'prod-5',
    name:         'Sac Noir Signature',
    slug:         'sac-noir-signature',
    description:  "Sac à bandoulière en cuir noir lisse. Quincaillerie argentée, intérieur organisé. La sobriété élégante à son apogée.",
    price:        69,
    comparePrice: 85,
    images:       [BAGS.noirMain, BAGS.noirDetail, BAGS.noirLife],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        9,
    tags:         ['noir', 'classique', 'bestseller'],
    featured:     false,
    active:       true,
    rating:       4.8,
    reviewCount:  62,
    createdAt:    '2023-11-15T00:00:00Z',
    updatedAt:    '2023-11-15T00:00:00Z',
  },

  // ── 6 ─ Sac Blanc Chic ───────────────────────────────────────────────────
  {
    id:           'prod-6',
    name:         'Sac Blanc Chic',
    slug:         'sac-blanc-chic',
    description:  "Sac structuré en cuir blanc ivoire, boucle dorée. Parfait pour l'été à Dubaï. Livré avec housse de protection.",
    price:        59,
    comparePrice: 75,
    images:       [BAGS.blancMain, BAGS.blancDetail, BAGS.blancLife],
    categoryId:   'cat-new',
    category:     { id: 'cat-new', name: 'Nouveautés', slug: 'nouveautes', position: 3 },
    stock:        14,
    tags:         ['blanc', 'été', 'nouveau'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  18,
    createdAt:    '2024-03-01T00:00:00Z',
    updatedAt:    '2024-03-01T00:00:00Z',
  },

  // ── 7 ─ Sac Marron Designer ──────────────────────────────────────────────
  {
    id:           'prod-7',
    name:         'Sac Marron Designer',
    slug:         'sac-marron-designer',
    description:  "Sac reporter en cuir marron camel, style architecturé. Deux compartiments, sangles ajustables. Allure intemporelle.",
    price:        75,
    comparePrice: 90,
    images:       [BAGS.marronMain, BAGS.marronDetail, BAGS.marronLife],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        7,
    tags:         ['marron', 'camel', 'designer'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  29,
    createdAt:    '2024-01-08T00:00:00Z',
    updatedAt:    '2024-01-08T00:00:00Z',
  },

  // ── 8 ─ Bracelet Jonc Or Rosé ────────────────────────────────────────────
  {
    id:           'prod-8',
    name:         'Bracelet Jonc Or Rosé',
    slug:         'bracelet-jonc-or-rose',
    description:  "Jonc rigide en laiton plaqué or rose 18 carats. Finition miroir. S'adapte à tous les poignets. Livré en écrin.",
    price:        28,
    comparePrice: 38,
    images:       [ACC.bracelet, ACC.braceletD],
    categoryId:   'cat-accessories',
    category:     { id: 'cat-accessories', name: 'Accessoires', slug: 'accessoires', position: 2 },
    stock:        20,
    tags:         ['bijou', 'or rosé', 'cadeau'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  19,
    createdAt:    '2024-01-05T00:00:00Z',
    updatedAt:    '2024-01-05T00:00:00Z',
  },

  // ── 9 ─ Lunettes Glamour Sable ───────────────────────────────────────────
  {
    id:           'prod-9',
    name:         'Lunettes Glamour Sable',
    slug:         'lunettes-glamour-sable',
    description:  "Monture acétate coloris sable, verres miroir dorés. Protection UV400. Style Old Money à la Dubai.",
    price:        32,
    comparePrice: 40,
    images:       [ACC.lunettes, ACC.lunettesD],
    categoryId:   'cat-accessories',
    category:     { id: 'cat-accessories', name: 'Accessoires', slug: 'accessoires', position: 2 },
    stock:        14,
    tags:         ['lunettes', 'été', 'tendance'],
    featured:     false,
    active:       true,
    rating:       4.5,
    reviewCount:  12,
    createdAt:    '2024-02-20T00:00:00Z',
    updatedAt:    '2024-02-20T00:00:00Z',
  },

  // ── 10 ─ Ceinture Cuir Premium ───────────────────────────────────────────
  {
    id:           'prod-10',
    name:         'Ceinture Cuir Premium',
    slug:         'ceinture-cuir-premium',
    description:  "Ceinture en cuir veau caramel, boucle dorée interchangeable. 3 tailles disponibles. Finition sellerie.",
    price:        35,
    comparePrice: 48,
    images:       [ACC.ceinture, ACC.ceintureD],
    categoryId:   'cat-accessories',
    category:     { id: 'cat-accessories', name: 'Accessoires', slug: 'accessoires', position: 2 },
    stock:        16,
    tags:         ['ceinture', 'cuir', 'classique'],
    featured:     false,
    active:       true,
    rating:       4.4,
    reviewCount:  8,
    createdAt:    '2024-01-28T00:00:00Z',
    updatedAt:    '2024-01-28T00:00:00Z',
  },

  // ── 11 ─ Foulard Soie Desert Rose ────────────────────────────────────────
  {
    id:           'prod-11',
    name:         'Foulard Soie Desert Rose',
    slug:         'foulard-soie-desert-rose',
    description:  "Foulard 100% soie, imprimé floral oriental. 90×90 cm. Cadeau idéal, livré en boîte MA LUXURY.",
    price:        22,
    comparePrice: 30,
    images:       [ACC.foulard, ACC.foulardD],
    categoryId:   'cat-new',
    category:     { id: 'cat-new', name: 'Nouveautés', slug: 'nouveautes', position: 3 },
    stock:        25,
    tags:         ['soie', 'foulard', 'cadeau', 'nouveau'],
    featured:     false,
    active:       true,
    rating:       4.8,
    reviewCount:  34,
    createdAt:    '2024-03-01T00:00:00Z',
    updatedAt:    '2024-03-01T00:00:00Z',
  },

  // ── 12 ─ Parfum Oud Dubai ────────────────────────────────────────────────
  {
    id:           'prod-12',
    name:         'Parfum Oud Dubai',
    slug:         'parfum-oud-dubai',
    description:  "Eau de parfum aux notes d'oud, rose et ambre. 50 ml. Flacon collector aux dorures arabisantes. L'essence de Dubai.",
    price:        45,
    comparePrice: 58,
    images:       [ACC.parfum, ACC.parfumD],
    categoryId:   'cat-bestsellers',
    category:     { id: 'cat-bestsellers', name: 'Best Sellers', slug: 'best-sellers', position: 4 },
    stock:        18,
    tags:         ['parfum', 'oud', 'cadeau', 'bestseller'],
    featured:     false,
    active:       true,
    rating:       4.9,
    reviewCount:  76,
    createdAt:    '2023-10-01T00:00:00Z',
    updatedAt:    '2023-10-01T00:00:00Z',
  },

  // ── 13 ─ Robe Luxe Dubai ─────────────────────────────────────────────────
  {
    id:           'prod-13',
    name:         'Robe Élégance Dubai',
    slug:         'robe-elegance-dubai',
    description:  "Robe longue en soie ivoire, coupe empire. Broderies dorées sur l'encolure. La tenue parfaite pour les soirées à Dubaï.",
    price:        99,
    comparePrice: 120,
    images:       [ACC.robe, ACC.robeDet],
    categoryId:   'cat-new',
    category:     { id: 'cat-new', name: 'Nouveautés', slug: 'nouveautes', position: 3 },
    stock:        6,
    tags:         ['robe', 'soirée', 'nouveau', 'luxe'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  11,
    createdAt:    '2024-04-01T00:00:00Z',
    updatedAt:    '2024-04-01T00:00:00Z',
  },

  // ── 14 ─ Escarpins Satin Gold ────────────────────────────────────────────
  {
    id:           'prod-14',
    name:         'Escarpins Satin Doré',
    slug:         'escarpins-satin-dore',
    description:  "Escarpins en satin champagne, talon aiguille 9 cm. Bouts pointus, petite bride dorée. Glamour absolu.",
    price:        65,
    comparePrice: 80,
    images:       [ACC.chaussure, ACC.chaussureD],
    categoryId:   'cat-bestsellers',
    category:     { id: 'cat-bestsellers', name: 'Best Sellers', slug: 'best-sellers', position: 4 },
    stock:        10,
    tags:         ['chaussures', 'doré', 'soirée', 'bestseller'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  22,
    createdAt:    '2024-02-14T00:00:00Z',
    updatedAt:    '2024-02-14T00:00:00Z',
  },

  // ── 15 ─ Robe de Luxe Turque ────────────────────────────────────────────────
  {
    id:           'prod-15',
    name:         'Robe de Luxe Orientale',
    slug:         'robe-luxe-orientale',
    description:  'Robe longue en tissu brodé de Turquie, coupe majestueuse. Broderies dorées sur l\'encolure et les manches. La pièce prestige de MA LUXURY — portée pour les grandes occasions, mariages et cérémonies. Tissu fluide, tombé impeccable. Importée directement de Turquie.',
    price:        110,
    comparePrice: 120,
    images:       ['/images/ROBESLUXETURQUE.png', '/images/ROBESOIREETURQUE.png', '/images/ROBEETETURQUE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        8,
    tags:         ['robe', 'luxe', 'orientale', 'cérémonie', 'turquie'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  34,
    createdAt:    '2024-03-10T00:00:00Z',
    updatedAt:    '2024-03-10T00:00:00Z',
  },

  // ── 16 ─ Robe de Soirée Turque ────────────────────────────────────────────
  {
    id:           'prod-16',
    name:         'Robe de Soirée Premium',
    slug:         'robe-soiree-premium',
    description:  'Robe de soirée en satin turc, silhouette sirène. Décolleté V raffiné, dos nu avec laçage doré. Idéale pour galas, soirées de prestige et dîners chics. Coloris profond, doublure intégrée. Importée de Turquie, contrôlée par MA LUXURY.',
    price:        89,
    comparePrice: 110,
    images:       ['/images/ROBESOIREETURQUE.png', '/images/ROBESLUXETURQUE.png', '/images/ROBECOURTEETE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        12,
    tags:         ['robe', 'soirée', 'satin', 'gala', 'turquie'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  27,
    createdAt:    '2024-03-15T00:00:00Z',
    updatedAt:    '2024-03-15T00:00:00Z',
  },

  // ── 17 ─ Robe d'Été Turque ────────────────────────────────────────────────
  {
    id:           'prod-17',
    name:         'Robe d\'Été Balnéaire',
    slug:         'robe-ete-balneaire',
    description:  'Robe d\'été légère en mousseline de Turquie. Imprimé floral oriental, bretelles fines, coupe fluide. Parfaite pour les journées ensoleillées, les promenades en bord de mer ou les soirées estivales décontractées. Lavable en machine, tissu qui ne froisse pas.',
    price:        45,
    comparePrice: 60,
    images:       ['/images/ROBEETETURQUE.png', '/images/ROBECOURTEETE.png', '/images/ROBESLUXETURQUE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        20,
    tags:         ['robe', 'été', 'légère', 'floral', 'turquie'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  18,
    createdAt:    '2024-04-01T00:00:00Z',
    updatedAt:    '2024-04-01T00:00:00Z',
  },

  // ── 18 ─ Robe Courte Chic ────────────────────────────────────────────────
  {
    id:           'prod-18',
    name:         'Robe Courte Casual Chic',
    slug:         'robe-courte-casual-chic',
    description:  'Robe courte en crêpe turc, coupe droite légèrement évasée. Style casual chic pour le quotidien élégant — bureau, déjeuner, shopping. Fermeture éclair invisible dans le dos, poches latérales discrètes. Disponible en plusieurs coloris. Importée de Turquie.',
    price:        35,
    comparePrice: 50,
    images:       ['/images/ROBECOURTEETE.png', '/images/ROBEETETURQUE.png', '/images/ROBESOIREETURQUE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        18,
    tags:         ['robe', 'courte', 'casual', 'quotidien', 'turquie'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  22,
    createdAt:    '2024-04-05T00:00:00Z',
    updatedAt:    '2024-04-05T00:00:00Z',
  },

  // ── 19 ─ Jean Premium Turque ─────────────────────────────────────────────
  {
    id:           'prod-19',
    name:         'Jean Slim Premium',
    slug:         'jean-slim-premium',
    description:  'Jean slim en denim premium de Turquie, coupe sculpture qui valorise la silhouette. Tissu stretch haute qualité, confort optimal toute la journée. Finitions soignées, rivets dorés, taille haute. Style moderne qui allie tendance et élégance casual. Importé directement de Turquie par MA LUXURY.',
    price:        65,
    comparePrice: 80,
    images:       [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=800&q=80&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80&fit=crop&auto=format',
    ],
    categoryId:   'cat-jeans',
    category:     { id: 'cat-jeans', name: 'Jeans', slug: 'jeans', position: 3 },
    stock:        25,
    tags:         ['jean', 'slim', 'denim', 'premium', 'turquie'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  41,
    createdAt:    '2024-03-20T00:00:00Z',
    updatedAt:    '2024-03-20T00:00:00Z',
  },

  // ── 20 ─ Jean Wide Leg Tendance ──────────────────────────────────────────
  {
    id:           'prod-20',
    name:         'Jean Wide Leg Élégant',
    slug:         'jean-wide-leg-elegant',
    description:  'Jean wide leg en denim épais de qualité supérieure, importé de Turquie. Coupe large et structurée, taille haute gainante. La pièce streetwear luxe de la saison — à porter avec un blazer et des escarpins pour un look chic total, ou en baskets pour le casual chic du quotidien.',
    price:        72,
    comparePrice: 80,
    images:       [
      'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=800&q=80&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1549062572-544a64fb0c56?w=800&q=80&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80&fit=crop&auto=format',
    ],
    categoryId:   'cat-jeans',
    category:     { id: 'cat-jeans', name: 'Jeans', slug: 'jeans', position: 3 },
    stock:        15,
    tags:         ['jean', 'wide leg', 'tendance', 'streetwear', 'turquie'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  19,
    createdAt:    '2024-04-10T00:00:00Z',
    updatedAt:    '2024-04-10T00:00:00Z',
  },

  // ── 21 ─ Tennis Luxe ─────────────────────────────────────────────────────
  {
    id:           'prod-21',
    name:         'Ensemble Tennis Luxe',
    slug:         'ensemble-tennis-luxe',
    description:  'Ensemble tennis sportswear haut de gamme importé de Turquie — jupe plissée et top assorti. Tissu technique stretch, respirant et anti-UV. Style sports club chic qui se porte aussi bien sur le court que lors d\'un brunch. Coupe flatteuse, finitions premium. Logo MA LUXURY brodé sur le côté.',
    price:        95,
    comparePrice: 120,
    images:       ['/images/tennis2.png', '/images/tennis2.png', '/images/tennis2.png'],
    categoryId:   'cat-tennis',
    category:     { id: 'cat-tennis', name: 'Tennis & Sport', slug: 'tennis', position: 4 },
    stock:        14,
    tags:         ['tennis', 'sport', 'luxe', 'ensemble', 'turquie'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  28,
    createdAt:    '2024-04-15T00:00:00Z',
    updatedAt:    '2024-04-15T00:00:00Z',
  },

  // ── 22 ─ Tenue Sport Élégante ────────────────────────────────────────────
  {
    id:           'prod-22',
    name:         'Tenue Sport Élégante',
    slug:         'tenue-sport-elegante',
    description:  'Tenue sport deux pièces (legging + crop top) en tissu technique premium de Turquie. Design épuré, bandes latérales dorées, coupe sculptante. Parfaite pour le sport, le yoga, les promenades ou le style athleisure chic. Tissu respirant, séchage rapide. Importée et sélectionnée par MA LUXURY.',
    price:        65,
    comparePrice: 85,
    images:       ['/images/tennis2.png', '/images/tennis2.png', '/images/ROBECOURTEETE.png'],
    categoryId:   'cat-tennis',
    category:     { id: 'cat-tennis', name: 'Tennis & Sport', slug: 'tennis', position: 4 },
    stock:        18,
    tags:         ['sport', 'legging', 'athleisure', 'tendance', 'turquie'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  15,
    createdAt:    '2024-04-20T00:00:00Z',
    updatedAt:    '2024-04-20T00:00:00Z',
  },

  // ── 23 ─ Tennis Set Pro ──────────────────────────────────────────────────
  {
    id:           'prod-23',
    name:         'Set Tennis Pro',
    slug:         'set-tennis-pro',
    description:  'Ensemble tennis deux pièces (jupe + top) en tissu technique respirant. Coupe sportswear chic, idéale sur le court ou en ville. Bandes contrastées, finitions premium. Importé de Turquie.',
    price:        75,
    comparePrice: 99,
    images:       ['/images/tennis2.png', '/images/tennis2.png', '/images/tennis2.png'],
    categoryId:   'cat-tennis',
    category:     { id: 'cat-tennis', name: 'Tennis & Sport', slug: 'tennis', position: 4 },
    stock:        16,
    tags:         ['tennis', 'sport', 'set', 'turquie'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  12,
    createdAt:    '2024-05-01T00:00:00Z',
    updatedAt:    '2024-05-01T00:00:00Z',
  },

  // ── 24 ─ Robe de Luxe Tunis ──────────────────────────────────────────────
  {
    id:           'prod-24',
    name:         'Robe de Luxe Tunis',
    slug:         'robe-luxe-tunis',
    description:  'Robe longue en tissu brodé, coupe empire élégante. Broderies florales sur l\'encolure et l\'ourlet. Portée pour les grandes occasions : mariages, soirées de gala, cérémonies. Doublure satinée intégrée. Importée de Turquie, sélectionnée par MA LUXURY.',
    price:        105,
    comparePrice: 120,
    images:       ['/images/robes de luxe.png', '/images/robe tunis.png', '/images/ROBESLUXETURQUE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        10,
    tags:         ['robe', 'luxe', 'tunis', 'cérémonie'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  29,
    createdAt:    '2024-05-01T00:00:00Z',
    updatedAt:    '2024-05-01T00:00:00Z',
  },

  // ── 25 ─ Robe Orientale Tunis ─────────────────────────────────────────────
  {
    id:           'prod-25',
    name:         'Robe Orientale Tunis',
    slug:         'robe-orientale-tunis',
    description:  'Robe mi-longue en crêpe à motif oriental, coupe évasée. Style bohème chic qui s\'adapte aussi bien aux soirées qu\'aux journées décontractées. Manches 3/4, ceinture dorée incluse. Importée de Turquie.',
    price:        55,
    comparePrice: 75,
    images:       ['/images/robe tunis.png', '/images/robes de luxe.png', '/images/ROBEETETURQUE.png'],
    categoryId:   'cat-robes',
    category:     { id: 'cat-robes', name: 'Robes', slug: 'robes', position: 2 },
    stock:        14,
    tags:         ['robe', 'orientale', 'tunis', 'chic'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  18,
    createdAt:    '2024-05-02T00:00:00Z',
    updatedAt:    '2024-05-02T00:00:00Z',
  },

  // ─────────────────── SACS NOUVEAUX ───────────────────────────────────────

  // ── 26 ─ Sac Cabas Coloré ────────────────────────────────────────────────
  {
    id:           'prod-26',
    name:         'Sac Cabas Coloré',
    slug:         'sac-cabas-colore',
    description:  'Grand cabas en cuir synthétique premium, coloris tendance. Fermeture magnétique, anses doubles renforcées, poche zippée intérieure. Idéal pour le quotidien, les courses et les journées chargées. Importé et sélectionné par MA LUXURY.',
    price:        52,
    comparePrice: 65,
    images:       ['/images/SAC1.png', '/images/SAC2.png', '/images/SAC3.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        20,
    tags:         ['sac', 'cabas', 'coloré', 'quotidien'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  23,
    createdAt:    '2024-05-03T00:00:00Z',
    updatedAt:    '2024-05-03T00:00:00Z',
  },

  // ── 27 ─ Sac Structuré Premium ────────────────────────────────────────────
  {
    id:           'prod-27',
    name:         'Sac Structuré Premium',
    slug:         'sac-structure-premium',
    description:  'Sac à main structuré en cuir grainé, silhouette architecturée. Boucle dorée sur le rabat, poignées courtes et sangle amovible. Compartiment principal spacieux, 2 poches plates intérieures. Le sac professionnel par excellence.',
    price:        78,
    comparePrice: 90,
    images:       ['/images/SAC36.png', '/images/sac7.png', '/images/SAC1.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        15,
    tags:         ['sac', 'structuré', 'professionnel', 'cuir'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  31,
    createdAt:    '2024-05-03T00:00:00Z',
    updatedAt:    '2024-05-03T00:00:00Z',
  },

  // ── 28 ─ Mini Sac Bonbon ─────────────────────────────────────────────────
  {
    id:           'prod-28',
    name:         'Mini Sac Bonbon',
    slug:         'mini-sac-bonbon',
    description:  'Mini sac compact aux couleurs pastel tendance, fermeture zip dorée. Format idéal pour les sorties : téléphone, clés, carte. Bandoulière chaîne amovible. Une touche de fantaisie chic pour chaque tenue.',
    price:        38,
    comparePrice: 50,
    images:       ['/images/sacbon1.png', '/images/sacbon2.png', '/images/sacbon3.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        25,
    tags:         ['sac', 'mini', 'bonbon', 'pastel', 'tendance'],
    featured:     false,
    active:       true,
    rating:       4.5,
    reviewCount:  17,
    createdAt:    '2024-05-04T00:00:00Z',
    updatedAt:    '2024-05-04T00:00:00Z',
  },

  // ── 29 ─ Sac Bonbon Collection ────────────────────────────────────────────
  {
    id:           'prod-29',
    name:         'Sac Bonbon Collection',
    slug:         'sac-bonbon-collection',
    description:  'Sac bandoulière de la collection Bonbon — format médium, cuir souple coloré. Zip principal et poche avant, doublure tissu, anneau porte-clés intégré. Disponible en plusieurs coloris. Parfait cadeau pour elle.',
    price:        45,
    comparePrice: 58,
    images:       ['/images/sacbonbon.png', '/images/sacbon4.png', '/images/sacbon6.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        18,
    tags:         ['sac', 'bonbon', 'collection', 'cadeau'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  14,
    createdAt:    '2024-05-04T00:00:00Z',
    updatedAt:    '2024-05-04T00:00:00Z',
  },

  // ── 30 ─ Sac Pro Business ─────────────────────────────────────────────────
  {
    id:           'prod-30',
    name:         'Sac Pro Business',
    slug:         'sac-pro-business',
    description:  'Sac professionnel en cuir premium, format cabas élégant. Convient pour un ordinateur 13 pouces, avec compartiments organisés. Anse portée main + sangle épaule ajustable. Le compagnon idéal des femmes actives et ambitieuses.',
    price:        82,
    comparePrice: 90,
    images:       ['/images/SACCPRO.png', '/images/SAC36.png', '/images/SAC2.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        12,
    tags:         ['sac', 'professionnel', 'business', 'laptop'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  26,
    createdAt:    '2024-05-05T00:00:00Z',
    updatedAt:    '2024-05-05T00:00:00Z',
  },

  // ── 31 ─ Ensemble Sac & Chaussures ────────────────────────────────────────
  {
    id:           'prod-31',
    name:         'Ensemble Sac & Chaussures',
    slug:         'ensemble-sac-chaussures',
    description:  'Pack coordonné sac à main + chaussures assortis — la tendance du look total. Cuir synthétique premium, coloris harmonisés. Le sac inclut une bandoulière amovible, les chaussures ont un talon de 6 cm. Importé de Turquie, contrôlé par MA LUXURY.',
    price:        88,
    comparePrice: 90,
    images:       ['/images/SAC ET CHAUUS.png', '/images/SACCHAUSSURE.png', '/images/SACHAUSS1.png'],
    categoryId:   'cat-bags',
    category:     { id: 'cat-bags', name: 'Sacs à Main', slug: 'sacs-a-main', position: 1 },
    stock:        10,
    tags:         ['sac', 'chaussures', 'ensemble', 'coordonné'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  38,
    createdAt:    '2024-05-05T00:00:00Z',
    updatedAt:    '2024-05-05T00:00:00Z',
  },

  // ─────────────────── CHAUSSURES ──────────────────────────────────────────

  // ── 32 ─ Escarpins Classiques ────────────────────────────────────────────
  {
    id:           'prod-32',
    name:         'Escarpins Classiques',
    slug:         'escarpins-classiques',
    description:  'Escarpins en cuir verni, bout pointu, talon aiguille 8 cm. Coloris nude intemporel qui allonge la silhouette. Semelle intérieure rembourrée pour le confort. À porter au bureau, en soirée, ou pour toute occasion habillée. Importés de Turquie.',
    price:        55,
    comparePrice: 70,
    images:       ['/images/chaussure1.png', '/images/chaussure2.png', '/images/chaussure3.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        18,
    tags:         ['chaussures', 'escarpins', 'classique', 'nude'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  34,
    createdAt:    '2024-05-06T00:00:00Z',
    updatedAt:    '2024-05-06T00:00:00Z',
  },

  // ── 33 ─ Mules Dorées ─────────────────────────────────────────────────────
  {
    id:           'prod-33',
    name:         'Mules Dorées Premium',
    slug:         'mules-dorees-premium',
    description:  'Mules à talon carré en satin doré, bride arrière élastiquée. Talons de 7 cm, semelle antidérapante. Le must-have de la saison — à porter avec une robe midi ou un pantalon palazzo. Style glamour garanti. Importées de Turquie.',
    price:        48,
    comparePrice: 65,
    images:       ['/images/chaussure4.png', '/images/chaussure5.png', '/images/chaussure6.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        20,
    tags:         ['chaussures', 'mules', 'doré', 'glamour'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  22,
    createdAt:    '2024-05-06T00:00:00Z',
    updatedAt:    '2024-05-06T00:00:00Z',
  },

  // ── 34 ─ Sandales Luxe ────────────────────────────────────────────────────
  {
    id:           'prod-34',
    name:         'Sandales Luxe Été',
    slug:         'sandales-luxe-ete',
    description:  'Sandales plates en cuir naturel avec détails tressés dorés. Semelle anatomique ultra-confort, tige réglable. Idéales pour les journées d\'été en ville, la plage ou les voyages. Style méditerranéen chic. Importées de Turquie.',
    price:        38,
    comparePrice: 52,
    images:       ['/images/CHAUSSURE.png', '/images/CHAUSSURE8.png', '/images/chaussure1.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        22,
    tags:         ['chaussures', 'sandales', 'été', 'plat'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  19,
    createdAt:    '2024-05-07T00:00:00Z',
    updatedAt:    '2024-05-07T00:00:00Z',
  },

  // ── 35 ─ Bottines Tendance ────────────────────────────────────────────────
  {
    id:           'prod-35',
    name:         'Bottines Tendance',
    slug:         'bottines-tendance',
    description:  'Bottines à lacets en cuir grainé, semelle crantée plateforme 3 cm. Style rock chic pour l\'automne-hiver. Fermeture éclair intérieure pour un enfilage facile. Parfaites avec un jean slim ou une robe midi. Importées de Turquie.',
    price:        72,
    comparePrice: 85,
    images:       ['/images/CH123.png', '/images/CHAUSS23.png', '/images/CHAUSS32.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        14,
    tags:         ['chaussures', 'bottines', 'tendance', 'lacets'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  16,
    createdAt:    '2024-05-07T00:00:00Z',
    updatedAt:    '2024-05-07T00:00:00Z',
  },

  // ── 36 ─ Ensemble Pull & Chaussures ──────────────────────────────────────
  {
    id:           'prod-36',
    name:         'Ensemble Pull & Chaussures',
    slug:         'ensemble-pull-chaussures',
    description:  'Look complet pull en maille fine + chaussures coordonnées. Pull oversize en laine mélangée, col rond, disponible en plusieurs coloris. Chaussures assortis en cuir, talon de 5 cm. Le duo parfait pour un style coordonné effortless.',
    price:        68,
    comparePrice: 85,
    images:       ['/images/PULLCHAUSSURE.png', '/images/chaussure2.png', '/images/CH123.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        12,
    tags:         ['pull', 'chaussures', 'ensemble', 'maille'],
    featured:     false,
    active:       true,
    rating:       4.5,
    reviewCount:  11,
    createdAt:    '2024-05-08T00:00:00Z',
    updatedAt:    '2024-05-08T00:00:00Z',
  },

  // ── 37 ─ Chaussettes Luxe ─────────────────────────────────────────────────
  {
    id:           'prod-37',
    name:         'Chaussettes Luxe Premium',
    slug:         'chaussettes-luxe-premium',
    description:  'Chaussettes en coton peigné premium, tissage renforcé aux talons et pointes. Motifs discrets dorés sur le pourtour, pack de 3 paires. Confort optimal toute la journée. À porter avec talons ou sneakers pour un détail chic et élégant.',
    price:        18,
    comparePrice: 25,
    images:       ['/images/CHAUSSETE.png', '/images/CHAUSSETE.png', '/images/chaussure3.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        40,
    tags:         ['chaussettes', 'luxe', 'confort', 'pack'],
    featured:     false,
    active:       true,
    rating:       4.4,
    reviewCount:  8,
    createdAt:    '2024-05-08T00:00:00Z',
    updatedAt:    '2024-05-08T00:00:00Z',
  },

  // ── 38 ─ Sac & Chaussures Assortis ───────────────────────────────────────
  {
    id:           'prod-38',
    name:         'Sac & Chaussures Assortis',
    slug:         'sac-chaussures-assortis',
    description:  'Pack duo sac à main + chaussures dans le même coloris. Cuir premium, finitions dorées. Le sac format médium avec bandoulière, les chaussures à talon bloc 6 cm. Idéal pour une tenue parfaitement coordonnée sans effort.',
    price:        85,
    comparePrice: 90,
    images:       ['/images/SACCHAUSSS.png', '/images/SACHAUSS1.png', '/images/SACCHAUSSURE.png'],
    categoryId:   'cat-chaussures',
    category:     { id: 'cat-chaussures', name: 'Chaussures', slug: 'chaussures', position: 5 },
    stock:        9,
    tags:         ['sac', 'chaussures', 'duo', 'coordonné'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  27,
    createdAt:    '2024-05-08T00:00:00Z',
    updatedAt:    '2024-05-08T00:00:00Z',
  },

  // ─────────────────── BIJOUX & OR ─────────────────────────────────────────

  // ── 39 ─ Collier Or Dubai ─────────────────────────────────────────────────
  {
    id:           'prod-39',
    name:         'Collier Or Dubai',
    slug:         'collier-or-dubai',
    description:  'Collier chaîne en or jaune 18 carats plaqué, maille gourmette fine. Fermoir mousqueton doré, longueur 45 cm. Inspiration joaillerie de Dubaï — élégance minimaliste qui sublime tous les décolletés. Livré en pochette velours MA LUXURY.',
    price:        35,
    comparePrice: 48,
    images:       [BIJOUX.collierJauneMain, BIJOUX.collierJauneDetail, BIJOUX.collierBlanc],
    categoryId:   'cat-bijoux',
    category:     { id: 'cat-bijoux', name: 'Bijoux & Or', slug: 'bijoux', position: 6 },
    stock:        30,
    tags:         ['bijoux', 'collier', 'or', 'dubai', 'cadeau'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  52,
    createdAt:    '2024-05-09T00:00:00Z',
    updatedAt:    '2024-05-09T00:00:00Z',
  },

  // ── 40 ─ Bracelet Or Fin ─────────────────────────────────────────────────
  {
    id:           'prod-40',
    name:         'Bracelet Or Fin',
    slug:         'bracelet-or-fin',
    description:  'Bracelet chaîne ultra-fin en or jaune plaqué 18 carats. Fermoir à ressort, longueur ajustable 16-18 cm. Se superpose avec d\'autres bracelets pour le look stacking tendance. Finition brillant miroir. Idéal comme cadeau pour une occasion spéciale.',
    price:        22,
    comparePrice: 32,
    images:       [BIJOUX.braceletJauneMain, BIJOUX.braceletJauneDetail, BIJOUX.braceletBlanc],
    categoryId:   'cat-bijoux',
    category:     { id: 'cat-bijoux', name: 'Bijoux & Or', slug: 'bijoux', position: 6 },
    stock:        35,
    tags:         ['bijoux', 'bracelet', 'or', 'stacking'],
    featured:     false,
    active:       true,
    rating:       4.8,
    reviewCount:  44,
    createdAt:    '2024-05-09T00:00:00Z',
    updatedAt:    '2024-05-09T00:00:00Z',
  },

  // ── 41 ─ Boucles d'Oreilles Or ────────────────────────────────────────────
  {
    id:           'prod-41',
    name:         'Boucles d\'Oreilles Or',
    slug:         'boucles-oreilles-or',
    description:  'Boucles d\'oreilles créoles en or jaune plaqué 18 carats, diamètre 3 cm. Design classique et intemporel qui s\'adapte à toutes les tenues — casual comme habillé. Fermoir à charnière sécurisé. Peau friendly, sans nickel. Livrées en écrin.',
    price:        18,
    comparePrice: 28,
    images:       [BIJOUX.bouclesJauneMain, BIJOUX.bouclesJauneDetail, BIJOUX.bouclesBlanc],
    categoryId:   'cat-bijoux',
    category:     { id: 'cat-bijoux', name: 'Bijoux & Or', slug: 'bijoux', position: 6 },
    stock:        28,
    tags:         ['bijoux', 'boucles', 'or', 'créoles'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  33,
    createdAt:    '2024-05-10T00:00:00Z',
    updatedAt:    '2024-05-10T00:00:00Z',
  },

  // ── 42 ─ Parure Complète Or ────────────────────────────────────────────────
  {
    id:           'prod-42',
    name:         'Parure Complète Or',
    slug:         'parure-complete-or',
    description:  'Parure trois pièces en or jaune plaqué 18 carats : collier + bracelet + boucles d\'oreilles. Design harmonisé, motifs arabisants gravés. Coffret cadeau inclus, parfait pour les mariages, fiançailles et anniversaires. La parure de prestige signée MA LUXURY.',
    price:        48,
    comparePrice: 0,
    images:       [BIJOUX.parureMain, BIJOUX.parureDetail, BIJOUX.parureLife],
    categoryId:   'cat-bijoux',
    category:     { id: 'cat-bijoux', name: 'Bijoux & Or', slug: 'bijoux', position: 6 },
    stock:        15,
    tags:         ['bijoux', 'parure', 'or', 'cadeau', 'mariage'],
    featured:     true,
    active:       true,
    rating:       5.0,
    reviewCount:  61,
    createdAt:    '2024-05-10T00:00:00Z',
    updatedAt:    '2024-05-10T00:00:00Z',
  },

  // ── 43 ─ Chaîne Or Premium ────────────────────────────────────────────────
  {
    id:           'prod-43',
    name:         'Chaîne Or Premium',
    slug:         'chaine-or-premium',
    description:  'Chaîne or premium maille forçat, plaquée or jaune 18 carats. Épaisseur 3 mm, longueur 50 cm, fermoir à ressort. S\'associe avec un pendentif ou se porte seule pour un look minimaliste chic. Résistante à l\'humidité, sans ternissement rapide.',
    price:        28,
    comparePrice: 40,
    images:       [BIJOUX.chaineJauneMain, BIJOUX.chaineJauneDetail, BIJOUX.chaineBlanc],
    categoryId:   'cat-bijoux',
    category:     { id: 'cat-bijoux', name: 'Bijoux & Or', slug: 'bijoux', position: 6 },
    stock:        22,
    tags:         ['bijoux', 'chaîne', 'or', 'premium'],
    featured:     false,
    active:       true,
    rating:       4.8,
    reviewCount:  29,
    createdAt:    '2024-05-11T00:00:00Z',
    updatedAt:    '2024-05-11T00:00:00Z',
  },

  // ── Parfums Arabes — Collection Ibraq 75 ml ─────────────────────────────────
  {
    id:           'prod-44',
    name:         'Oud Al Malik 75 ml',
    slug:         'oud-al-malik-75ml',
    description:  'Parfum oriental intense 75 ml. Note de tête : bergamote & cardamome. Cœur : oud du Camboge & rose de Taïf. Fond : ambre, musc blanc & santal. Longévité exceptionnelle — 10 à 12h. Flacon luxe doré avec bouchon sculpté. Collection Ibraq Perfumes, Arabie Saoudite.',
    price:        49,
    comparePrice: 65,
    images:       [PARFUMS.oudMain, PARFUMS.oudDetail, PARFUMS.oudLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        30,
    tags:         ['parfum', 'oud', 'oriental', 'luxe', 'ibraq', 'arabie'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  18,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
  {
    id:           'prod-45',
    name:         'Rose de Taïf 75 ml',
    slug:         'rose-de-taif-75ml',
    description:  'Parfum floral précieux 75 ml. Note de tête : rose de Taïf & litchi. Cœur : pivoine, jasmin & patchouli. Fond : musc, vanille & bois de cachemire. Subtil et envoûtant, idéal pour femme. Flacon nacré rose champagne. Collection Ibraq Perfumes.',
    price:        45,
    comparePrice: 58,
    images:       [PARFUMS.roseMain, PARFUMS.roseDetail, PARFUMS.roseLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        25,
    tags:         ['parfum', 'rose', 'floral', 'femme', 'ibraq', 'taif'],
    featured:     true,
    active:       true,
    rating:       4.8,
    reviewCount:  14,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
  {
    id:           'prod-46',
    name:         'Ambre Sultan 75 ml',
    slug:         'ambre-sultan-75ml',
    description:  'Parfum chaud et enveloppant 75 ml. Note de tête : épices orientales & safran. Cœur : ambre gris & résine de benjoin. Fond : musc noir, oud & cèdre. Sillage généreux et persistant. Mixte — jour et soirée. Flacon ambré avec détails dorés. Collection Ibraq Perfumes.',
    price:        42,
    comparePrice: 55,
    images:       [PARFUMS.ambreMain, PARFUMS.ambreDetail, PARFUMS.ambreLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        20,
    tags:         ['parfum', 'ambre', 'oriental', 'mixte', 'ibraq', 'épices'],
    featured:     false,
    active:       true,
    rating:       4.7,
    reviewCount:  11,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
  {
    id:           'prod-47',
    name:         'Santal Mystique 75 ml',
    slug:         'santal-mystique-75ml',
    description:  'Parfum boisé crémeux 75 ml. Note de tête : bergamote & poivre rose. Cœur : santal de Mysore & iris. Fond : vanille, vétiver & musc blanc. Chaleureux et sensuel, parfait pour l\'automne-hiver. Flacon ivoire mat. Collection Ibraq Perfumes.',
    price:        38,
    comparePrice: 50,
    images:       [PARFUMS.santalMain, PARFUMS.santalDetail, PARFUMS.santalLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        18,
    tags:         ['parfum', 'santal', 'boisé', 'crémeux', 'ibraq'],
    featured:     false,
    active:       true,
    rating:       4.6,
    reviewCount:  9,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
  {
    id:           'prod-48',
    name:         'Musc Tahara 75 ml',
    slug:         'musc-tahara-75ml',
    description:  'Parfum musc pur 75 ml — signature des palais d\'Arabie. Note de tête : aldéhydes & fleurs blanches. Cœur : musc blanc & rose. Fond : musc animé, ambre & cire d\'abeille. Propre, laiteux et addictif. Flacon blanc nacré. Collection Ibraq Perfumes.',
    price:        35,
    comparePrice: 45,
    images:       [PARFUMS.muskMain, PARFUMS.muskDetail, PARFUMS.muskLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        35,
    tags:         ['parfum', 'musc', 'blanc', 'pur', 'ibraq', 'arabie'],
    featured:     false,
    active:       true,
    rating:       4.8,
    reviewCount:  22,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
  {
    id:           'prod-49',
    name:         'Jasmin Doré 75 ml',
    slug:         'jasmin-dore-75ml',
    description:  'Parfum floral oriental 75 ml. Note de tête : mandarine & néroli. Cœur : jasmin sambac & tubéreuse. Fond : bois de oud, musc doré & patchouli. Élégant et moderne, taillé pour la femme de Dubaï. Flacon doré transparent. Collection Ibraq Perfumes.',
    price:        44,
    comparePrice: 57,
    images:       [PARFUMS.jasminMain, PARFUMS.jasminDetail, PARFUMS.jasminLife],
    categoryId:   'cat-parfum',
    category:     { id: 'cat-parfum', name: 'Parfums Arabes', slug: 'parfums', position: 10 },
    stock:        22,
    tags:         ['parfum', 'jasmin', 'floral', 'oriental', 'femme', 'ibraq'],
    featured:     true,
    active:       true,
    rating:       4.9,
    reviewCount:  16,
    createdAt:    '2025-01-10T00:00:00Z',
    updatedAt:    '2025-01-10T00:00:00Z',
  },
]

export type MockProduct  = (typeof MOCK_PRODUCTS)[0]
export type MockCategory = (typeof MOCK_CATEGORIES)[0]
